### ISSUE TITLE
Request: Ability to block block steps :p

### ISSUE THREAD

**Issue by SomeoneWeird** [buildkite/feedback#169]
We have a manual unblock step for production deploys (as I'm sure a lot of other people do)
```
build -> test -> staging -> block -> prod
```

Issue is, it can be unblocked as soon as the pipeline has started. It would be good to be able to force it to wait for all steps behind it to go green, before you're allowed to unblock it.

**Comment by keithpitt** [comment]
@SomeoneWeird interesting idea! Why do you want to stop someone from clicking it before the build has finished? It won't continue on until the previous builds pass anyway...

**Comment by SomeoneWeird** [comment]
That's true, but we've had issues in the past with stuff failing in staging, and getting deployed to prod without being checked properly. Definitely a failure in our test suite/deployment, but being able to block somebody until it's deployed gives a bit of a safety net for somebody to notice

There are a few other things we could do to prevent this happening though, so if you're not keen more than welcome to close

**Comment by keithpitt** [comment]
Ah, here's another idea for you...

Instead of defining the `unblock` step as the last thing, if you'd like to hold off, do something like this:

```
steps:
  - command: "./buildkite/make.sh"
  - wait
  - command: "./buildkite/test.sh"
  - wait
  - command: "./buildkite/deploy-pipeline.sh"
```
