### ISSUE TITLE
Specify default agent rules at top-level in `pipeline.yml`

### ISSUE THREAD

**Issue by jamesottaway** [buildkite/feedback#173]
https://buildkite.com/docs/agent/build-pipelines mentions that only `env` and `steps` are the only permitted top-level YML options.

We use a non-standard queue name for our auto-scaling cluster of agents, so we end up specifying the `agent` rules in each and every step under `steps`:

```
- name: 'something'
  command: true
  agent:
    queue: elastic
```

For a pipeline with 20 steps this adds up to 40 extraneous LOC.

It would be great if we could add something like this to the top of the YML config:

```
---
agent:
  queue: elastic

steps:
  - name: 'something'
    command: true
```

**Comment by mdub** [comment]
I've also multiple agent queues, and am also finding it annoying to repeat the queue-name for every step.

I've taken to solving it by generating the pipeline YAML, e.g.

```
buildkite-agent pipeline upload <<YAML
steps:
  - name: Test
    command: ./auto/test
    agents:
      queue: ${BUILDKITE_AGENT_META_DATA_QUEUE?}
  - name: Package
    command: ./auto/package
    agents:
      queue: ${BUILDKITE_AGENT_META_DATA_QUEUE?}
  - name: Release
    command: ./auto/release
    branches: master
    agents:
      queue: ${BUILDKITE_AGENT_META_DATA_QUEUE?}
YAML
```

but that's also ugly.

I like @jamesottaway's idea of pipeline-wide defaults.

Another idea: uploaded pipeline steps should use the _current_ queue by default, rather than the one called "default".

**Comment by keithpitt** [comment]
So we could probably support pipeline wide agents pretty easily. @mdub how's this?

```yaml
buildkite-agent pipeline upload <<YAML
agents:
  queue: ${BUILDKITE_AGENT_META_DATA_QUEUE?}

steps:
  - name: Test
    command: ./auto/test

  - name: Package
    command: ./auto/package

  - name: Release
    command: ./auto/release
    branches: master
YAML
```

Making the queue default to the current queue would raise some other problems, especially around peeps that have `queue=pipeline-uploaders`

One of the questions I have is around overrides, would we just merge each one together? If you define a custom set of agent rules for a step, would that override anything defined globally? This is how ENV current works, but I just wanted to confirm.

**Comment by gazmania** [comment]
+1

The above looks good to me. I'm not sure about defaulting to the current queue, i'd rather declaratively target specific queues, and to being able to do it at the top level would eliminate the need for lots of repeating in each step.

Override wise I'd totally expect step level to merge into pipeline level with step overriding on a clash

**Comment by roblugton** [comment]
@keithpitt That's how I'd expect anything declared outside the step scope to behave. 

Anything declared in the global scope would be overwritten if it was decalred in the scope of a step.

**Comment by gtirloni** [comment]
Just wanted to chime in and say this would be very useful to us. I'm just starting adding agents with different capabilities and would like to filter them either based on queue (or a set of keys I defined in the agent meta-data). I don't know if the latter is considered here, please let me know if I should open a separate issue for that.

**Comment by gtirloni** [comment]
Started experimenting with multiple agents per host (we've got some beefy boxes) and it's painful to look at the YAML now :)

**Comment by gtirloni** [comment]
@petemounce thanks, that worked great for simplying our pipeline.yml. However, the issue is that we'd either have to target a single build node with this (single point of failure) or again have the problem of different steps from the same pipeline running on different nodes in a distinct build.

Using a script to generate the rest of the YAML looks like the way to go but it makes everything more complex to maintain. Ideally we just want to say "run all steps in this pipeline on the same agent that got assigned the first step".

**Comment by nikskiz** [comment]
Will this be supported in a YAML located within the repo (i.e `.buildkite/pipeline.yaml`) rather than the UI?

**Comment by callumj** [comment]
Seconding @nikskiz, we have this in `.buildkite/pipeline.yml` and it seems it doesn't work?

```

agents:
  stack: buildkite20190131a
```

**Comment by jbarnette** [comment]
@keithpitt Did this feature regress at some point this year? I'm seeing steps run on the `default` queue with a pipeline like this:

```yaml
agents:
  queue: deploy

steps:
  ...
```

**Comment by 007lva** [comment]
I have Buildkite agent 3.26 and it's not working for me either:

```yml
agents:
  queue: "default"

steps:
  ...
```
