### ISSUE TITLE
Can we support "PR checking" in pipeline.yml ?

### ISSUE THREAD

**Issue by melonq** [buildkite/feedback#209]
Hi team,

Recently, we migrate our CI pipeline to BuildKite and it looks awesome expect some tiny points.

One of the pain points is "We want to use `pipeline.yml` to config the steps that can or cannot run for PR, but there're no keywords to support it." So we have to use `dynamic pipeline` to implement it.

 But most of our repos are only use `dynamic pipeline` like:
```
#!/bin/bash
# Put some steps can be run for PR (like Tests)

if test "$BUILDKITE_BRANCH" = "master" && test "$BUILDKITE_PULL_REQUEST" = "false"; then
  # Put some steps should only run for origin/master (like Release)
fi
```
You can see that often the only thing in the dynamic pipeline script is checking the `PR` env var. 

So I'm wondering if we can have a key-pair in `pipeline.yml` to decide if this step should run for PR.  Similar with the `branches: 'master'`.

Thanks

**Comment by keithpitt** [comment]
@melonq thanks for the feedback!

So maybe something like this?

```
steps:
  - command: "test.sh"
    pull_requests: false

  - command: "test.sh"
    pull_requests: true
```

And I suppose we'd default it to `pull_requests: true`?

I wonder what the expected behaviour would be if you set `branches` and `pull_requests`:

```
steps:
  - command: "test.sh"
    pull_requests: false
    branches: "master"
```
