### ISSUE TITLE
Ability to cancel a blocked pipeline

### ISSUE THREAD

**Issue by timbod7** [buildkite/feedback#213]
We are using the "wait and block pipeline"  step as a review before critical infrastructure changes are made, as described here:

https://building.buildkite.com/terraform-techniques-with-buildkite-81c0d6619f24#.qwt56b2n1

If for some reason the reviewer doesn't wish the change to go ahead, there is currently no means to cancelling the build. 

The workaround currently is that you have to unblock the build, then quickly cancel before the next step proceeds. This is, obviously, less than ideal.

**Comment by lsimoneau** [comment]
We have a similar situation where this would be useful. We continuously deploy our changes into our staging environment, and then require manual unblocking to deploy into production.

If we discover a serious bug in a release candidate, we'd like to be able to cancel the build to ensure that no one accidentally clicks "Continue" and squashes production with a broken version. In our instance a fix for the bug had already been deployed to prod, but the original buggy branch hadn't been, so someone came around and incorrectly deployed the old version because they thought it was still just waiting on deployment.

**Comment by lsimoneau** [comment]
It would also be nice if cancelling a blocked build allowed you to specify a reason for the cancellation, so you could make it clear the change is not fit for release.

**Comment by keithpitt** [comment]
So there's another way to approach the problem you described @lsimoneau and @timbod7. Check this:

```yaml
steps:
  - command: "test.sh"

  - block: "Deploy to Production :rocket:"
    fields:
     - select: "Are you sure you're cool to deploy this release?"
       key: "confirm"
       default: "Yes"
       options:
         - Yes
         - No
     - text: "Notes"
       key: "notes"
       hint: "Any additional information you want to add to this deployment"

  - command: "deploy.sh"
```

So here we have a pipeline that allows you to choose "Yes/No" when you go to deploy it. It'll also ask the user to provide some additional notes if they wish.

In your `deploy.sh` file, you can do something like this:

```bash
CONFIRM_DEPLOY=$(buildkite-agent meta-data get confirm)
DEPLOY_NOTES=$(buildkite-agent meta-data get notes)

if [[ "$CONFIRM_DEPLOY" == "No" ]]; then
  echo "DEPLOYMENT CANCELLED!"
  echo $DEPLOY_NOTES
  exit 1
fi
```

So you're forcing a fail of the deploy tasks. The notes won't be as visual, but this should mostly work!
