### ISSUE TITLE
[Feature Request] File or Path Filter | Sparse Git Checkout

### ISSUE THREAD

**Issue by poida** [buildkite/feedback#243]
Hi,

I'd like to be able to only run a job in a pipeline if a particular file (or maybe matching path/glob) has changed.

I'd like to use this to only run our docker build and publish step if the `Dockerfile` has changed.

E.g.

```
steps:
  - label: ':hammer: build docker'
    command: ./scripts/build_publish_docker.sh
    branches: 'master'
    path: Dockerfile
    agents:
      queue: dev

 - wait

 - label: ':tornado: run tests'
 ...
```

Thanks!
