### ISSUE TITLE
Steps restricted to "master" branch should not run for pull-request builds

### ISSUE THREAD

**Issue by mdub** [buildkite/feedback#252]
We have attempted to restrict certain steps to running on builds from the "master" branch, using [branch filters](https://buildkite.com/docs/pipelines/branch-configuration), e.g.

```yaml
steps:
  - name: Test
    command: ./auto/test
  - name: Release
    branch: master   # <=== only release on master
    command: ./auto/release
```

Unfortunately, when some random user submits a pull-request from their "master" branch (a poor but annoyingly common practice), then the branch filter above will match, and the "Release" step would run. It's difficult to imagine a scenario in which that is desirable. 

At REA, we've been bitten by this a few times, with "Release" or "Deploy" steps inadvertently running on pull-requests.  These days we tend to avoid use of branch-filters, instead resorting to generating the pipeline dynamically, e.g.

```
#!/bin/bash -eu

cat <<YAML
steps:
  - name: Test
    command: ./auto/test
YAML

if test "$BUILDKITE_BRANCH" = "master" && test "$BUILDKITE_PULL_REQUEST" = "false"; then
cat <<YAML
  - name: Release
    command: ./auto/release
YAML
fi
```

IMHO, branch filters should _never_ match on pull-requests.  In fact, for PRs, I reckon `$BUILDKITE_BRANCH` should be prefixed with a fork name, e.g. "randomuser:master", rather than just "master".

@keithpitt: I think we chatted F2F about this a while back? It seems related to #203.
