### ISSUE TITLE
passing environment to triggered jobs

### ISSUE THREAD

**Issue by tnh** [buildkite/feedback#253]
Currently, we have a pipeline like:

```
env:
  AWS_DEFAULT_REGION: ap-southeast-2
  ENVIRONMENT: drprod
  ACCOUNT: prod

steps:
- trigger: something-infrastructure
  label: ':tractor: something'
  build:
    message: ${BUILDKITE_MESSAGE}
    commit: HEAD
    branch: master
    env:
      ENVIRONMENT: drprod
      ACCOUNT: prod

- wait

- trigger: another-thing-infrastructure
  label: ':minibus: Deploy another thing ervices'
  build:
    message: ${BUILDKITE_MESSAGE}
    commit: HEAD
    branch: master
    env:
      ENVIRONMENT: drprod
      ACCOUNT: prod

```

what I dont like is

- having to specify the `env` for each of the steps that is the same
- needing to define the environment variables

I tried to do something like this but it doesnt work:
```
- trigger: another-thing-infrastructure
  label: ':minibus: Deploy another thing ervices'
...
    env:
      ENVIRONMENT: ${ENVIRONMENT}
```

I'm wondering if it would be possible to either

- define an environment that is passed down to all steps, including triggered steps; or
- be able to reference environment variables eg: `ENVIRONMENT: ${ENVIRONMENT}`

**Comment by sj26** [comment]
Hmm, it's YAML, so you could use anchors and references:

```
env:
  AWS_DEFAULT_REGION: ap-southeast-2
  ENVIRONMENT: drprod
  ACCOUNT: prod

steps:
- trigger: something-infrastructure
  label: ':tractor: something'
  build:
    message: ${BUILDKITE_MESSAGE}
    commit: HEAD
    branch: master
    env: &TRIGGER_ENV
      ENVIRONMENT: drprod
      ACCOUNT: prod

- wait

- trigger: another-thing-infrastructure
  label: ':minibus: Deploy another thing ervices'
  build:
    message: ${BUILDKITE_MESSAGE}
    commit: HEAD
    branch: master
    env: *TRIGGER_ENV
```

Finding a YAML reference is hard, but anchors and references are covered in this tutorial:

https://rhnh.net/2011/01/31/yaml-tutorial/
