### ISSUE TITLE
Env var interpolation in trigger step doesn't work

### ISSUE THREAD

**Issue by legalosLOTR** [buildkite/feedback#260]
As per the docs, I have a trigger step in my pipeline.yml that looks like this:
```  
- trigger: 'deploy'
    async: true
    branches: 'master'
    label: 'Schedule Deploy'
    build:
      branch: "$BUILDKITE_BRANCH"
      commit: "$BUILDKITE_COMMIT"
```

This leads to a "deploy" build with branch=$BUILDKITE_BRANCH. Basically the string ($BUILDKITE_BRANCH) and not the actual branch name. I also tried `${BUILDKITE_BRANCH}` but same issue there.
