### ISSUE TITLE
Support a list of checkboxes in block fields

### ISSUE THREAD

**Issue by toolmantim** [buildkite/feedback#280]
At the moment, if you want people to choose from a list of items with [custom block fields](https://buildkite.com/docs/pipelines/block-step) it's very difficult. The common way people are doing it is pre-filling a textarea, and then asking people to remove any lines from the text area. And then using that value, split on newline, as the chosen options. This is error prone and a bit clunky.

A better way might be a way for people to use an array of checkbox options in the block form…

If you we had a new checkbox option, and someone used the `key` field of `servers-to-deploy`, and someone unblocked it selecting 2 of the 10 available options, the meta-data keys/values could be:

```
servers-to-deploy-count=2
servers-to-deploy-1=The First Server
servers-to-deploy-2=The Second Server
```

To use those values, you could iterate over them using bash:

```bash
if buildkite-agent meta-data exists "servers-to-deploy-count"; then
  for i in `seq 1 $(buildkite-agent meta-data get "servers-to-deploy-count")`; do
    echo "Deploying server $(buildkite-agent meta-data get "servers-to-deploy-${i}")..."
  done
fi
```

If nothing is selected, then there should be no `servers-to-deploy-count` key.

**Comment by lucas044** [comment]
This would be a really cool feature, thanks @toolmantim

**Comment by DuBistKomisch** [comment]
:+1: I'd love to be able to have checkboxes, and even tie the skip field of future steps to them.

**Comment by nhuray** [comment]
I'd love to have this to choose the service I want to deploy from a pipeline !

**Comment by mcchas** [comment]
👍 any chance of this happening?

**Comment by Ardesco** [comment]
Any update on this, it's one thing that's really missing right now.

**Comment by monemihir** [comment]
+1

**Comment by JacobBarba** [comment]
This would be huge for our team - in AWS we have collections of Lambdas that make up various services and frequently we only want to alter a few at a time during a deploy. We currently have a cascading system of bash scripts and manual selections in place that allow us to selectively deploy updates but the code is ugly and the manual process is ... annoying :)

**Comment by ghost** [comment]
Would really like to see this feature.  Have migrated this to their feature request board on buildkite community in the hope of some traction there too.  https://forum.buildkite.community/t/support-a-list-of-checkboxes-in-block-fields/470

**Comment by ticky** [comment]
Hey folks, we're still putting together the docs proper, but this feature just rolled out! 🥳

You can now add a `multiple: true` attribute to your `select` fields, and they will show up as a list of checkboxes! On the meta-data side, rather than having a numbered set of meta-data fields, we delimit with a single newline character, so it's always just one meta-data value for you to work with, in a single call, and can be iterated over pretty simply!

**Comment by DuBistKomisch** [comment]
@ticky awesome thanks :+1: just trying this out now, how does it interact with the `default` attribute? I'd like all of them to be selected by default

**Comment by ticky** [comment]
@DuBistKomisch you can submit multiple values like this (please judge it not by the extremely contrived example 😅):

```yaml
steps:
  - block: "Release"
    prompt: "Fill out the details for release"
    fields:
      - select: "Type"
        key: "release-type"
        multiple: true
        default:
        - "alpha"
        - "canary"
        - "beta"
        - "stable"
        options:
        - label: "Alpha"
          value: "alpha"
        - label: "Canary"
          value: "canary"
        - label: "Beta"
          value: "beta"
        - label: "Stable"
          value: "stable"
  - command: "buildkite-agent meta-data get release-type"
```

![image](https://user-images.githubusercontent.com/282113/59645742-5dcdd280-9128-11e9-8f13-0bdd31933f41.png)
