### ISSUE TITLE
Prevent agents from returning to the queue during the 'wait' step

### ISSUE THREAD

**Issue by dtruong0** [buildkite/feedback#281]
Prevent agents returning to the queue during the wait step for builds that run steps in parallel.

I have a pipeline that looks like this
```
  - name: 'Test 1’
    command: scripts/buildkite/tests.sh
    env:
      PARALLEL_JOB: 0
    agents:
      queue: QUEUE
      aws:instance-id: __INSTANCE_ID1__
  - name: 'Test 2’
    command: scripts/buildkite/tests.sh
    env:
      PARALLEL_JOB: 1
    agents:
      queue: QUEUE
      aws:instance-id: __INSTANCE_ID2__
  - wait
  - name: 'Make Version Report'
    command: scripts/buildkite/buildkite-version-report.sh
    env:
      PARALLEL_JOB: 0
    agents:
      queue: QUEUE
      aws:instance-id: __INSTANCE_ID1__
```
  `QUEUE` and` __INSTANCE_ID1__` are substituted during the pipeline upload step

Say Tests 1 completes in 5 minutes and Test 2 completes in 20
During the 15 minute wait Test 1’s agent will return to the queue of available agents.
As a result the build can be left hanging because Test 1’s build agent was stolen by another build.

**Comment by toolmantim** [comment]
Hey David! Sorry you're having troubles with this. I wonder if there's a way to avoiding targeting specific instance ids in your build pipeline? Then you could use any available agent, rather than relying on the dependence of a specific agent. This is usually how people accomplish this, and if there's some shared state either push it to S3 or use a build artifact.

**Comment by dtruong0** [comment]
Yeah this is a shared state issue because the testing environment is setup in the previous steps.
During the pipeline upload step the second agent is chosen using the api to find the next available.

Is it possible to set the queue meta-data or change the agent prioritisation during a build?

**Comment by toolmantim** [comment]
Thanks for the details. Hmm it's a tricky one. And I'm trying to figure it out, but I don't fully understand what the limitations are.

You can't set agent meta-data or agent prioritisation during a build I'm afraid. You can stop agents and start them again?

I'm afraid what you're trying to do doesn't really gel with the primitives Buildkite supplies, at least in the way you're trying to set this up. But there has to be a way to accomplish what you need. Is there no way to store the state somewhere?

Or could you just make each of the initial steps do the version report as well?

```yaml
  - name: 'Test 1’
    commands:
      - scripts/buildkite/tests.sh
      - scripts/buildkite/buildkite-version-report.sh
    env:
      PARALLEL_JOB: 0
  - name: 'Test 2’
    commands:
      - scripts/buildkite/tests.sh
      - scripts/buildkite/buildkite-version-report.sh
    env:
      PARALLEL_JOB: 1
```
