### ISSUE TITLE
Pass environment variables from parent build

### ISSUE THREAD

**Issue by nullobject** [buildkite/feedback#304]
When I trigger another pipeline from a build, it would be nice if some of the environment vars from the parent build were automatically provided to the child build.

For example:

- `BUILDKITE_PARENT_BUILD_ID`
- `BUILDKITE_PARENT_BUILD_NUMBER`
- `BUILDKITE_PARENT_BUILD_URL`
- `BUILDKITE_PARENT_PIPELINE_SLUG`
- etc

Currently I am manually mapping these environment vars manually every time I trigger my "docker-deploy" build pipeline:

```yml
  - label: ":rocket: Staging"
    trigger: docker-deploy
    branches: master
    build:
      message: "Deploy $BUILDKITE_PIPELINE_SLUG to staging"
      env:
        BUILDKITE_PARENT_BUILD_ID: "$BUILDKITE_BUILD_ID"
        BUILDKITE_PARENT_BUILD_NUMBER: "$BUILDKITE_BUILD_NUMBER"
        BUILDKITE_PARENT_BUILD_URL: "$BUILDKITE_BUILD_URL"
        BUILDKITE_PARENT_PIPELINE_SLUG: "$BUILDKITE_PIPELINE_SLUG"
```
