### ISSUE TITLE
Overriding environment variable in a pipeline doesn't work when steps are uploaded from agent

### ISSUE THREAD

**Issue by lankaapura** [buildkite/feedback#323]
I have a windows buildkite agent configured to upload steps as per documentation. However, it seems that overriding environment variables don't work with it. But it works fine if I defined same steps on the portal without uploading thru the agent.

```yaml
env:
  module_name: "Web"
  project_path: "..\\Source\\Web.csproj"

steps:

  - command: "powershell.exe build\\build.ps1"
    label: ":hammer: Build"

  - wait

  - command: "powershell.exe build\\publish-website.ps1"
    label: "Deploy Web"
    env:
      module_name: "Web"
      project_path: "..\\Source\\Web.csproj"
    branches: "master"

  - wait

  - command: "powershell.exe build\\publish-website.ps1"
    label: "Deploy Identity Server"
    env:
      module_name: "IdentityServer"
      project_path: "..\\Source\\IdentityServer.csproj"
    branches: "master"

  - wait
  
  - block: "Release"
    prompt: "Fill out the details for release."
    fields: 
      - text: "Release Name"
        key: "release-name"
        required: false
      - text: "Changelog"
        key: "release-notes"
        required: false
      - select: "Type"
        key: "release-type"
        default: "patch"
        options:
        - label: "Major"
          value: "major"
        - label: "Minor"
          value: "minor"
        - label: "Patch"
          value: "patch"
      - text: "Rlease Version"
        key: "release-version"
        hint: "Keep empty to use auto-generated build number."
        required: false

  - command: "powershell.exe .buildkite\\release.ps1"
    label: "Publish :rocket:"
```
