### ISSUE TITLE
buildkite environment variable substitution in 3.0

### ISSUE THREAD

**Issue by joscha** [buildkite/feedback#345]
I am not sure if there is an easy way to fix this, or even detect a way to fix this, but I wanted to file it anyway so other people will find it when they google.
We had a step in our scripts that dynamically generates some inline bash, like this:

```bash
bk_gen_dynamic_step_inception() {
  local cmd="$1"
  local agent_role="$2"
  local timeout_minutes="${3:-2}"
  local branches="${4:-}"

  command=$(cat <<BASH
set -eu -o pipefail
        pipeline_file=\$(mktemp --suffix .yaml --tmpdir pipeline.XXXXXXXXXX)
        trap "rm -rf \"\${pipeline_file}\"" EXIT
        ${cmd} >"\${pipeline_file}"
        buildkite-agent pipeline upload "\${pipeline_file}"
        buildkite-agent artifact upload "\${pipeline_file}"
BASH
)

  bk_comment "pipeline upload step for:"
  bk_comment "${cmd}"
  bk_step \
      --label ":pipeline:" \
      --command "${command}" \
      --agent-role "${agent_role}" \
      --timeout "${timeout_minutes}" \
      --branch-filter "${branches}"
}
```

basically we use this to produce a new step on-demand by amending the pipeline.
The YAML produced from this is as follow:

```yaml
# pipeline upload step for:
# my_command
  - name: ':pipeline:'
    command: |
        set -eu -o pipefail
        pipeline_file=$(mktemp --suffix .yaml --tmpdir pipeline.XXXXXXXXXX)
        trap "rm -rf \"${pipeline_file}\"" EXIT
        my_command >"${pipeline_file}"
        buildkite-agent pipeline upload "${pipeline_file}"
        buildkite-agent artifact upload "${pipeline_file}"
    branches: ''
    timeout_in_minutes: 2
    parallelism: 1
    artifact_paths: ''
    concurrency: ''
    concurrency_group: ''
    skip: false
    agents:
      role: agent_role
```

on the Buildkite Agent 2, this would work as expected, as `$pipeline_file` would be resolved at runtime of the step. But for Agent 3.0 the `$pipeline_file` would be resolved at the time of generating the step (e.g. *before* buildkite-agent upload), hence the generated bash would be incorrect and fail the step at runtime.

I wonder if undefined env variables (what `$pipeline_file` would be at the time of step generation) on inline-commands is really expected? I can obviously add another `\`, but I think my expectation would be for interpolation only to happen on non-heredoc-style yaml.
