### ISSUE TITLE
Feature: plugins from local paths

### ISSUE THREAD

**Issue by joscha** [buildkite/feedback#363]
We have a mono repository and I would like to write a few Buildkite plugins for internal things that are in this mono repository (a local stack that we start up in CI to do some e2e testing for example), hence I would like to co-locate the plugin code and the local stack code, but it seems as if the plugin only takes `org/repo`, not anything like `/path/from/checkout/to/plugin`.

**Comment by lox** [comment]
That's strange, it should work! Mind sending us a pipeline.yml that isn't working to hello@buildkite.com

**Comment by joscha** [comment]
@lox maybe my definition is wrong?

Does this look sane:

```yaml
    plugins:
     /local_stack: ~
```

?

**Comment by lox** [comment]
At the minute our plugin gear makes the assumption that there is a git repository that can be cloned:

https://github.com/buildkite/agent/blob/master/bootstrap/bootstrap.go#L464

So this works for me:

```
steps:
  - label: "Test local plugin"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    plugins:
      "/Users/lachlan/Projects/buildkite/docker-compose-buildkite-plugin": ~
```

Plugins that don't involve a git checkout are something we could consider, but not a thing yet.
