### ISSUE TITLE
It appears that a block step is also a wait step, can I change this?

### ISSUE THREAD

**Issue by gerrywastaken** [buildkite/feedback#407]
Given the following pipeline

```yml
steps:
  - command: echo "tests"
  - block: ":shipit: staging"
  - command: echo "staging deploy" && sleep 30 && exit 1
  - block: ":shipit: prod"
  - command: echo "blocked by staging deploy"
```

After all stages are unblocked we end up with the last command waiting for the second command to successfully exit, even though no `wait` step was specified.

![block_step_also_waits](https://user-images.githubusercontent.com/71481/41699291-8b6211ea-7566-11e8-9a81-35e02cb939b9.png)

The docs for `wait` specify:
> A wait step waits for all previous steps to have successfully completed before allowing following jobs to continue.

The docs for `block`:
> A block step is used to pause the execution of a build and wait on a team member to unblock it via the web or the API.

But perhaps a more appropriate description is:
> A block step is used to pause the execution of a build and wait for both a team member to unblock it via the web or the API; and for all previous steps to have successfully completed.

The docs do say this:
> Once all steps before the block have completed, the pipeline will pause and wait for a team member to unblock it. 

But that's not the same as saying it will cause a `wait` regardless of it's blocked state. This is also a problem because `block` does not support `continue_on_failure`.

Is there any way for `block` to only wait to be unblocked and not wait for success of previous steps?

**Comment by gerrywastaken** [comment]
Am I misunderstanding something?

**Comment by andreitchaltsev** [comment]
I bumped into exactly the same issue. Is there a solution to remove "wait" feature from "block" step?

**Comment by nikskiz** [comment]
After some trail and error I have managed to get a block step to work so it is not dependant on any other block steps:
```
steps:
  - block: " Test 1"
    depends_on: ~
    key: "test-1"

  - label: TEST 1
    commands:
      - echo "test 1"
    depends_on: "test-1"

  - block: " Test 2"
    depends_on: ~
    key: "test-2"

  - label: TEST 2
    commands:
      - echo "test 2"
    depends_on: "test-2"

  - block: ":amazon-rds: Test 3"
    depends_on: ~
    key: "test-3"

  - label: TEST 3
    commands:
      - echo "test 3"
    depends_on: "test-3"
```
