### ISSUE TITLE
Feature: retry on text pattern(s) matched in build log output

### ISSUE THREAD

**Issue by petemounce** [buildkite/feedback#413]
I would like to be able to automatically retry builds via configuring patterns at a step / pipeline level.

```yaml
- label: foo
  command: echo foobar
  retry:
    automatic:
      log_output:
        - pattern: /foo/ # match regexp
          channels: [stdout, stderr] # in either stdout or stderr
          limit: 2 # as exit_status
        - pattern: "foobar" # match string exactly within any line
          limit: 4
```

I wouldn't want the patterns to include the optional timestamp that I saw it's possible to turn on via agent configuration.

I'd like this because
* I can automatically retry if a step times out - because usually, that's a reasonable log output to watch for
* it's a very flexible way to reduce flake-noise but in a very targeted way.
