### ISSUE TITLE
Block steps can be locked down

### ISSUE THREAD

**Issue by raynix** [buildkite/feedback#417]
![image](https://user-images.githubusercontent.com/1613641/42355002-ff6e341c-810d-11e8-83a1-c11448b0216e.png)
So I'd hope there's an option to make `pack and deliver` step locked down(greyed out) until `deploy for QA` is successful.

**Comment by sj26** [comment]
We spoke about this over email! But here, for posterity, you can do this by splitting your pipeline into two pieces, and only uploading the second after it should be unblockable.

```yaml
# .buildkite/pipeline.yml
steps:
- command: echo building a thing
- block: Test the thing?
- command: echo testing a thing
- wait
- command buildkite-agent pipeline upload .buildkite/pipeline.deploy.yml
```

```yaml
# .buildkite/pipeline.deploy.yml
steps:
- block: Deploy the thing?
- command: echo deploy the thing
```

The first one does a couple of steps and includes a block step, and only uploads the second pipeline at the very end, meaning the deploy button won't appear or be unblockable until you know that it's a deployable build.
