### ISSUE TITLE
Easier Trigger Step based on Block step result

### ISSUE THREAD

**Issue by jmendiara** [buildkite/feedback#427]
Use Case:
* Ask the user about some data using a `Block step`
* `Trigger step` based on the response

Making this today is possible, but may involve multiple intermediate step + `pipeline upload` 

Trigger only allows `key`:`value`, in `build.env` or `build.meta_data` where value can be a discrete value or an env var that will be substituted by the Agent. There is no easy way to express "the value is this metadata the user entered before" 

Something like this... I know variable substitution is performed on upload, this should be evaluated in the backend, but I hope you get the idea
 ```yml
- block: "Request Release"
  fields:
    - text: "Code Name"
      key: "RELEASE_NAME"

- trigger: "data-generator"
   label: ":package: Generate data"
   build:
     meta_data:
       release-name: "$(buildkite meta-data RELEASE_NAME)"
     env:
       RELEASE_NAME: "$(buildkite meta-data RELEASE_NAME)" 
```
