### ISSUE TITLE
Block step field validation

### ISSUE THREAD

**Issue by jmendiara** [buildkite/feedback#430]
I may become handy to include some input validation in Block step inputs

example
```yml
steps:
  - block: "Request Release"
    fields:
      - text: "Code Name"
        key: "release-name"
        required: false 
        validations:
          "@url": "Should be an URL"  # @indicates built-in validations
          "@required": # Uses default validation message
          "/^[0-9]+$/": "Should be a number" # regex validation
```
