### ISSUE TITLE
Feature: Fail all parallel steps if 1 of them fails

### ISSUE THREAD

**Issue by raynix** [buildkite/feedback#441]
Given 

```
steps:
  - label: "step 1.a"
    command:
      - ./1.a.sh

  - label: "step 1.b"
    command:
      - ./1.b.sh

  - wait
  - label: "step 2"

```
If step 1.a fails I would like step 1.b to fail or to be cancelled immediately as it's a waste of time for a buildkite agent to complete 1.b in such scenario.
