### ISSUE TITLE
Allow branch/tag names to be matched with regular expressions

### ISSUE THREAD

**Issue by sgrimm-sg** [buildkite/feedback#459]
One of my projects has a tagging scheme where we use a raw semver number like 1.34.2 as the git tag when publishing a new release.

On CircleCI, our "deploy the release" step had a regex filter to look for those tags:

```yaml
  filters:
    tags:
      only: /^\d+\.\d+\.\d+.*/
    branches:
      ignore: /.*/
```

But as far as I can tell, Buildkite doesn't let us do a digits-only match like the above snippet because the branch filter uses shell-style globbing. We end up having to do

```yaml
    branches:
      - "*.*.*"
```

and then add a sanity check in our build script to check to see if the current revision's tag really looks like a version number.

It'd be handy if Buildkite would let us specify a regex instead of a shell glob pattern here.
