### ISSUE TITLE
agent support for jsonnet

### ISSUE THREAD

**Issue by jmendiara** [buildkite/feedback#468]
When developing multiple complex pipelines, a repetition problem may arise.
You can end having the same steps defined in different pipelines, and maintaining them implies modifying lots of files

One approach can be "yaml templates" + "concatenation"
```yml
# steps.yml
deploy: &deploy
  label: "Deploy"
  command: deploy.sh

undeploy: &undeploy
  label: "Undeploy"
  command: undeploy.sh

test: &test
  label: "Test"
  command: test.sh
```

```yml
# pipelineA.yml
steps: 
  - *deploy
  - wait
  - *undeploy
```

```yml
# pipelineB.yml
steps: 
  - *deploy
  - wait
  - *test
  - wait
  - *undeploy
```

And upload the pipeline this way, as yml does not have an "import" directive
`cat steps.yml pipelineA.yml | buildkite-agent pipeline upload`
`cat steps.yml pipelineB.yml | buildkite-agent pipeline upload`

This solves a single use case making a workaround: both `pipelineA.yml` and `pipelineB.yml` are not valid yaml.

Supporting [jsonnet](https://jsonnet.org) can solve that use case and lots more. There is a [go official implementation](https://github.com/google/go-jsonnet) and will allow us to code dynamic pipelines.

```jsonnet
// steps.libsonnet
{
  deploy: {
    label: 'Deploy',
    command: 'deploy.sh',
  },
  undeploy: {
    label: 'Undeploy',
    command: 'undeploy.sh',
  },
  test: {
    label: 'Test',
    command: 'test.sh',
  },
}
```

```jsonnet
// pipelineA.jsonnet
local steps = import 'steps.libsonnet';
{ 
  steps: [
    steps.deploy,
    'wait',
    steps.undeploy,
  ],
}
```

`buildkite-agent pipeline upload pipelineA.jsonnet`
