### ISSUE TITLE
Make "source" a standard step filter

### ISSUE THREAD

**Issue by moensch** [buildkite/feedback#507]
So far the only filter we have for steps is `branches`. We find ourselves often writing pipelines where we do different things depending on whether they're running as a `schedule` or via `webhook` or via `ui`.
Today, we always do dynamic pipelines. Though it would be awesome if we didn't have to do that but instead use something like this in a step:

```
steps:
 - label: foo
   command: something
   sources: 'ui|schedule'
```

Or
`sources: '!ui'`
