### ISSUE TITLE
Ability to disable a step

### ISSUE THREAD

**Issue by cirode** [buildkite/feedback#55]
This would be used to temporarily remove a step in the pipeline

eg: Disable deploys to production.. etc etc

**Comment by keithpitt** [comment]
👋 We pushed out a way to mark "steps" as `skipped` within your Pipeline.yml file:

``` yaml
steps:
  - command: "test.sh"
    label: ":console:"
    skip: true

  - command: "test.sh"
    label: ":console:"
    skip: "it's rad"

  - command: "test.sh"
    label: ":console:"
    skip: "<strong>lol</strong>"
```

![image](https://cloud.githubusercontent.com/assets/25882/14736096/37b75112-08b8-11e6-984c-04a41dcb3c02.png)

![image](https://cloud.githubusercontent.com/assets/25882/14736106/3cbc8d94-08b8-11e6-94c8-7df1b053dec4.png)

![image](https://cloud.githubusercontent.com/assets/25882/14736112/42a286a0-08b8-11e6-87a4-6f0524e95ffc.png)
